apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-yszcmrpl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/go-yszcmrpl:2470ead52d355ec54126b0b92332ad8ed4fe5b25
          name: container-image
